version: '3'

services:
  nginx:
    image: nginx:nimai
    container_name: nginx
    build:
      context: ./requirements/nginx #where is my docker file
    depends_on:
      - wordpress
    volumes:
      - ${VOLUME_WEB}:/var/www/html
#      - web:/var/www/html
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    networks:
      - inception-network

  wordpress:
    image: wordpress:nimai
    build:
      context: ./requirements/wordpress
#    restart: always
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception-network
    env_file:
      - .env
    volumes:
      - ${VOLUME_WEB}:/var/www/html/
#      - web:/var/www/html/

  mariadb:
    image: mariadb:nimai
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - ${VOLUME_DB}:/var/lib/mysql
#      - db:/var/lib/mysql
    networks:
      - inception-network
    restart: always
    env_file:
      - .env

#  adminer:
#    image: adminer:nimai
#    build:
#      context: ./requirements/bonus/adminer
#    container_name: adminer
#    restart: always
#    depends_on:
#      - mariadb
#      - wordpress
#    ports:
#      - "8080:8080"
#    networks:
#      - inception-network




networks:
  inception-network:
      driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: volume
      device: ${VOLUME_DB}
      o: bind
  web:
    driver: local
    driver_opts:
      type: volume
      device: ${VOLUME_WEB}
      o: bind
