version: '3'

services:
  nginx:
    image: ngnix:nimai
    container_name: nginx
    build:
      context: ./requirements/nginx #where is my docker file
    depends_on:
      - wordpress
    volumes:
      - web:/var/www/html
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    networks:
      - my-network

  wordpress:
    image: wordpress:nimai
    build:
      context: ./requirements/wordpress
#    restart: always
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - web:/var/www/html

  mariadb:
    image: mariadb:nimai
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network
    restart: always
    env_file:
      - .env




networks:
  my-network:

volumes:
  db:
    driver_opts:
      type: local
      device: ${VOLUME_DB}
      o: bind
  web:
    driver_opts:
      type: local
      device: ${VOLUME_WEB}
      o: bind
