version: '3.9'

services:
  nginx:
    image: ngnix
    container_name: nginx
    build: ./requirements/nginx #where is my docker file
    ports:
      - 443:443
    restart: always
    env_file:
      - .env
    networks:
      - my-network

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
#    restart: always
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - my-network
    env_file:
      - .env
    volumes:
      - web:/var/www/html

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - my-network
    env_file:
      - .env


networks:
  my-network:


volumes:
  db:
    driver_opts:
      type: local
      device: ${VOLUME_DB}
      o: bind
  web:
    driver_opts:
      type: local
      device: ${VOLUME_WEB}
      o: bind
